apiVersion: v1
kind: Service
metadata:
  name: guestbook
  labels:
    app: guestbook
    team: red
    env: staging
spec:
  type: ClusterIP
  selector:
    app: guestbook
    team: red
  ports:
    - name: http
      port: 80
      targetPort: 3000
