apiVersion: v1
kind: Service
metadata:
  name: guestbook
  labels:
    app: guestbook
    env: dev
spec:
  type: ClusterIP
  selector:
    app: guestbook
  ports:
    - name: http
      port: 80
      targetPort: 3000
